CTCTRADERS-1455 - Reimplement controller endpoint to use customs-reference-data over static values
hmrc/transit-movements-trader-reference-data pull request #42
Opened 2020-12-15 17:54 UTC by amaalali

2020-12-16 07:49 UTC, chris-ianson commented on app/api/controllers/DangerousGoodsCodesController.scala
> +          case _ =>
If we're returning 404 for this should we maybe log an error also (including code)

2020-12-16 07:50 UTC, chris-ianson commented on app/api/controllers/PreviousDocumentTypeController.scala
> +          case _ =>
If we're returning 404 for this should we maybe log an error also (including code)

2020-12-16 07:51 UTC, chris-ianson commented on app/api/controllers/SpecialMentionController.scala
> +      Ok(Json.toJson(specialMentionService.specialMention))
Do we need a failure case here?

2020-12-16 07:51 UTC, chris-ianson commented on app/api/controllers/TransportModeController.scala
> +            NotFound
If we're returning 404 for this should we maybe log an error also (including code)

2020-12-16 07:56 UTC, chris-ianson requested changes
Couple of comments. What's the reasoning behind a 404 on failure? The reason I'm asking is because none of our consuming services fail gracefully (as far as I'm aware) if they can't get data.I we thinking the calling service will error out anyway (and should kick off a pagerduty)

2020-12-16 15:47 UTC, chris-ianson approved these changes

2020-12-16 15:59 UTC, amaalali commented
test this please

2020-12-17 12:05 UTC, amaalali commented
test this please

2020-12-17 12:13 UTC, merged